[package]
name = "toy_pcd_wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
